### ISSUE TITLE
环境部署

### ISSUE THREAD

**Issue by glwmt** [f4cknet/pyhackme#1]
师傅，这个环境怎么部署啊？是docker吗？没看懂欸

**Comment by f4cknet** [comment]
https://www.bilibili.com/video/BV1tV411X7Lf/  我录了安装视频。。 还没全部开发完，等全部写完打包成镜像吧

glwmt ***@***.***> 于2024年1月19日周五 10:27写道：

**Comment by f4cknet** [comment]
拉取最新代码，执行docker-compose up -d
